abstract: to_json() method for all objects
author: Kentaro Kuribayashi <kentaro@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: MIT
name: UNIVERSAL-to_json
no_index: 
  directory: 
    - inc
    - t
requires: 
  Best: 0
  JSON::Syck: 0
version: 0.03
